name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "Frontend/**"

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm install

      - name: Build frontend
        run: |
          cd Frontend
          npm run build

      - name: Deploy frontend to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --follow-symlinks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: "eu-north-1"
          SOURCE_DIR: "Frontend/dist"
